Fixes to allow flake8
techservicesillinois/splunk-soar-template pull request #7
Opened 2022-12-20 17:41 UTC by edthedev

2022-12-20 17:42 UTC, edthedev commented
Build fails here because it tries to deploy. Rebasing on main after #6 is merged should resolve this.

2023-01-10 14:36 UTC, edthedev commented
> Build fails here because it tries to deploy. Rebasing on `main` after #6 is merged should resolve the current build failure.

We did rebase on `main` after #6 was merged, and it did solve the build errors. 

As Trillian would say, "We have normality. Anything you still cannot deal with is, therefore, your own problem." Or in this case, a new unrelated problem.

2023-01-10 20:54 UTC, ddriddle requested changes
Please remove `tests/.gitkeep` unless needed.

2023-01-10 21:05 UTC, mpitcel approved these changes

2023-01-10 21:06 UTC, ddriddle approved these changes

2023-01-10 21:08 UTC, merged